version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py create_plans && python manage.py create_dummy_teacher && python manage.py update_dummy_teacher --name 'John Smith' --specialization 'Physics' && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # The frontend Dockerfile builds and serves with Nginx, no system Nginx needed
    # No separate nginx service, no manual port management

volumes:
  postgres_data:
